blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),  

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),

    # Example: /test/
    #url(r'^test/$', TestPostLV.as_view(), name='post_test'),
    # Example: /test/word/
    url(r'^test/(?P<word>[\w]+)/$', TestPostLV.as_view(), name='post_test'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>

<style>
    body{
        background:black;
    }
    .form-row{
        color:#CFCEDA;
    }
{#    @import url(//fonts.googleapis.com/earlyaccess/nanumpenscript.css);#}
{#      h1 { font-family: 'Nanum Pen Script', cursive; }#}

</style>

<body>

<div id="header">
    <h2 class="maintitle"><a href="{% url 'home' %}">&nbsp;<span class="glyphicon glyphicon-home"></span></a></h2>
{#<h2 class="maintitle"><a href="{% url 'home' %}">쉽고 빠르게 장고로 만든 웹 사이트</a></h2>#}
    {% if user.is_active %}
    <h4 class="welcome">환영합니다,
                <strong>{% firstof user.get_short_name user.get_username %}님</strong> /
                <a href="{% url 'password_change' %}">비밀번호 변경</a> /
                <a href="{% url 'logout' %}">로그아웃</a>
    </h4>
    {% else %}
    <h4 class="welcome">환영합니다, 익명의 사용자님 /
                <a href="{% url 'login' %}">로그인</a> /
                <a href="{% url 'register' %}">회원가입</a>
    </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'bookmark:index' %}">북마크 ▽</a>
        <ul>
            <li><a href="{% url 'bookmark:add' %}">북마크 추가</a></li>
            <li><a href="{% url 'bookmark:change' %}">북마크 업데이트/삭제</a></li>
        </ul>
    </li>
    <li><a href="{% url 'blog:index' %}">블로그 ▽</a>
        <ul>
            <li><a href="{% url 'blog:add' %}">게시글 추가</a></li>
            <li><a href="{% url 'blog:change' %}">게시글 업데이트/삭제</a></li>
        </ul>
    </li>
    <li><a href="{% url 'photo:index' %}">앨범 ▽</a>
        <ul>
            <li><a href="{% url 'photo:album_add' %}">앨범 추가</a></li>
            <li><a href="{% url 'photo:album_change' %}">앨범 업데이트/삭제</a></li>
            <li>사진 ▷
                <ul>
                    <li><a href="{% url 'photo:photo_add' %}">사진 추가</a></li>
                    <li><a href="{% url 'photo:photo_change' %}">사진 업데이트/삭제</a></li>
                </ul>
            </li>
        </ul>

    </li>
    <li><a href="{% url 'blog:post_archive' %}">게시글 보관함</a></li>
    <li><a href="{% url 'blog:search' %}">검색하기</a></li>
    <li><a href="{% url 'admin:index' %}">사용자</a></li>
</div>
{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}7조의 장고 홈페이지입니다.{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
<link href='http://fonts.googleapis.com/css?family=Open+Sans|Lobster' rel='stylesheet' type='text/css'>

<style>
.Lobster { font-family: 'Lobster', cursive;}
</style>

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="https://www.popsci.com/sites/popsci.com/files/images/2016/12/giphy_38.gif" style="height:260px;"/></a>
        <div class="Lobster">The Djangogers</div>
{#        <div id="hometxt">#}
{#            <h4 style="margin: 0;">웹 사이트에 오신 것을 환영합니다.</h4>#}
{#        </div>#}

    </div>

{#    <hr style="margin: 5px 0;">#}

{#    <h2>원하는 프로그램 선택하기</h2>#}
{##}
{#    <table id="applist">#}
{#        <tr>#}
{#        <td><b><i><a href="{% url 'bookmark:index' %}">북마크</a></i><b></td>#}
{#        <td>나만의 북마크를 저장/업데이트하거나, 삭제하기.</td>#}
{#        <td class="Edit"><i><a href="{% url 'bookmark:add' %}">추가</a></i></td>#}
{#        <td class="Edit"><i><a href="{% url 'bookmark:change' %}">변경</a></i></td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#        <td><b><i><a href="{% url 'blog:index' %}">내 블로그</a></i><b></td>#}
{#        <td>이벤트를 기록하거나 취미, 기술 등 내 블로그에 기록하기</td>#}
{#        <td class="Edit"><i><a href="{% url 'blog:add' %}">추가</a></i></td>#}
{#        <td class="Edit"><i><a href="{% url 'blog:change' %}">변경</a></i></td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#        <td><b><i><a href="{% url 'photo:index' %}">사진</a></i><b></td>#}
{#        <td>내 사진을 업로드하기(앨범을 삭제하면 앨범 내의 모든 사진이 삭제됩니다.)</td>#}
{#        <td class="Edit"><i><a href="{% url 'photo:album_add' %}">추가</a></i></td>#}
{#        <td class="Edit"><i><a href="{% url 'photo:album_change' %}">변경</a></i></td>#}
{#        </tr>#}
{#    </table>#}
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; The Djangogers 2017
</div>
{% endblock footer %}